spring:
  application:
    name: customer-service
  data:
    mongodb:
      username: minhtv
      password: minhtv
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090